import dotenv from "dotenv";
dotenv.config();

import connectDB from "../config/database";
import User from "../models/user.model";
import BlogCategory from "../models/blog-category.model";
import Blog from "../models/blog.model";
import { createBlogSchema } from "../validations/blog.validations";
import * as blogService from "../services/blog.service";
import { USER_ROLES } from "../constants/roles";

async function testExactUiPayload() {
  console.log("=== TESTING EXACT UI FORM PAYLOAD FOR BLOG CREATION ===");
  await connectDB();

  const testAdmin = await User.findOne({ role: USER_ROLES.ADMIN, isDeleted: false });
  if (!testAdmin) throw new Error("No admin found in DB");

  const cat = await BlogCategory.findOne({ isDeleted: false });
  if (!cat) throw new Error("No category found in DB");

  // Exact payload as generated by AdminBlogForm when user clicks Publish Article
  const exactUiPayload = {
    title: "How to Prepare for Your First Software Developer Interview | JobBox",
    slug: "how-to-prepare-for-your-first-software-developer-interview",
    excerpt: "Learn how to prepare for your first software developer interview, from technical fundamentals and project preparation to behavioral questions.",
    content: "## Preparation Overview\n\nHere are the top tips for your first software developer interview:\n\n- Master data structures\n- Practice system design\n- Prepare behavioral questions\n\nGood luck with your journey!",
    categoryId: cat._id.toString(),
    coverImageUrl: "https://res.cloudinary.com/vl9suovo/image/upload/v1788344024/Job-portal/blogs/sample.jpg",
    coverImagePublicId: "Job-portal/blogs/sample",
    coverImageAlt: "Modern developer desk with laptop and interview notes",
    tags: ["interview", "software-developer", "career"],
    isFeatured: true,
    isTrending: false,
    status: "PUBLISHED", // Uppercase as sent by frontend!
    seo: {
      metaTitle: "How to Prepare for Your First Software Developer Interview | JobBox",
      metaDescription: "Learn how to prepare for your first software developer interview, from technical fundamentals and project preparation to behavioral questions.",
      keywords: ["software developer interview", "React interview"],
      canonicalUrl: "https://your-domain.com/blog/how-to-prepare-for-your-first-software-developer-interview",
    },
  };

  console.log("[STEP 1] Validating payload against Zod createBlogSchema...");
  const validated = await createBlogSchema.parseAsync({ body: exactUiPayload });
  console.log("[PASS] Zod validation parsed successfully:", {
    title: validated.body.title,
    status: validated.body.status, // normalized to "published"
    categoryId: validated.body.categoryId,
  });

  console.log("[STEP 2] Executing blogService.createBlog()...");
  const created = await blogService.createBlog(validated.body as any, testAdmin._id.toString());
  console.log("[PASS] Blog created successfully in DB:", {
    id: created._id.toString(),
    slug: created.slug,
    status: created.status,
    publishedAt: created.publishedAt,
    viewsCount: created.viewsCount,
  });

  // Clean up
  await Blog.deleteOne({ _id: created._id });
  console.log("[CLEANUP] Deleted test blog.");

  console.log("\n[SUCCESS] Exact UI payload test passed with 100% fidelity.");
  process.exit(0);
}

testExactUiPayload().catch((err) => {
  console.error("[FAIL]", err);
  process.exit(1);
});
