export const NOTIFICATION_TYPES = {
  JOB_ALERT: "JOB_ALERT",
  APPLICATION_UPDATE: "APPLICATION_UPDATE",
  NEW_MESSAGE: "NEW_MESSAGE",
  SYSTEM_ALERT: "SYSTEM_ALERT",
  POST_LIKED: "POST_LIKED",
  POST_COMMENTED: "POST_COMMENTED",
  COMMENT_REPLIED: "COMMENT_REPLIED",
  CONNECTION_REQUEST: "CONNECTION_REQUEST",
  CONNECTION_ACCEPTED: "CONNECTION_ACCEPTED",
  POST_REPOSTED: "POST_REPOSTED",
} as const;

export type NotificationType =
  typeof NOTIFICATION_TYPES[keyof typeof NOTIFICATION_TYPES];
